spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${URL}
    username: ${USERNAME}
    password: ${PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
      use-new-id-generator-mappings: false
    show-sql: false
    properties:
      format_sql: true
      generate-ddl: true
  redis:
    port: ${REDIS-PORT}
    host: ${REDIS-HOST}

jwt:
  header: ${HEADER}
  prefix : ${PREFIX}
  secret: ${JWT-SECRET}
  access: ${TOKEN-EXP}
  refresh: ${REFRESH-EXP}