spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/
    username: sa
    password:
      driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false
    show-sql: false
    format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect