spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${URL}
    username: ${DB-USERNAME}
    password: ${DB-PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      generate-ddl: false
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
    show-sql: true
  jackson:
    property-naming-strategy: SNAKE_CASE

fcm:
  certification: clip-b0e37-firebase-adminsdk-d0p4v-f8da8698c3.json

redis:
  port: ${REDIS-PORT}
  host: ${REDIS-HOST}

jwt:
  header: ${HEADER}
  prefix : ${PREFIX}
  secret-key: ${JWT-SECRET}
  access-exp: ${ACCESS-EXP}
  refresh-exp: ${REFRESH-EXP}