spring:
  jackson:
    property-naming-strategy: SNAKE_CASE
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${URL}
    username: ${LOCAL-DB-USERNAME}
    password: ${LOCAL-DB-PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      generate-ddl: true
      hibernate:
        use_sql_comments: true
        format_sql: true